#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Rebuild mirrors/owned reject* from SKK, scoped to app_catalog interest.

Filters domainset + non_ip reject* using:
  patches/interest_seed.json (domains/suffixes/keywords/vendors/reject_interest)
  patches/tombstones.yaml (never include)
  patches/app_catalog.yaml (surge_interest=true — documented in README scope)

Idempotent. Does not modify mirrors/skk.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SEED = ROOT / "patches" / "interest_seed.json"
TOMB = ROOT / "patches" / "tombstones.yaml"
CATALOG = ROOT / "patches" / "app_catalog.yaml"
SKK = ROOT / "mirrors" / "skk" / "List"
OWNED = ROOT / "mirrors" / "owned" / "List"
OWNED_README = ROOT / "mirrors" / "owned" / "README.md"

DOMAINSET_FILES = [
    "reject.conf",
    "reject_extra.conf",
    "reject_phishing.conf",
]
NON_IP_FILES = [
    "reject.conf",
    "reject-drop.conf",
    "reject-no-drop.conf",
]

MULTI_PART_PUBLIC = frozenset(
    {
        "com.cn",
        "net.cn",
        "org.cn",
        "gov.cn",
        "co.uk",
        "com.au",
        "co.jp",
        "com.hk",
        "com.tw",
        "com.sg",
        "co.kr",
        "com.br",
        "co.nz",
    }
)

HEADER_DOMAINSET = """\
# owned curated reject DOMAINSET (V6.1 app-scoped)
# 自建精简 reject：仅覆盖 patches/app_catalog.yaml 中 surge_interest=true 的 App
# Owned curated reject for apps in app_catalog (surge_interest=true)
# NOT a full SKK mirror — 非完整 SKK 镜像；其他 App 请用 upstream SKK:
#   https://ruleset.skk.moe  或  mirrors/skk/List/domainset/
# Generated by scripts/slim_owned_reject_by_apps.py; tombstones applied
# Source: mirrors/skk (cache only); do not whole-replace without this filter
"""

HEADER_NON_IP = """\
# owned curated reject RULE-SET / non_ip (V6.1 app-scoped)
# 自建精简 reject：仅覆盖 app_catalog surge_interest=true Apps
# Owned curated reject for catalog apps — NOT a full SKK mirror
# Outside scope: https://ruleset.skk.moe or mirrors/skk/List/non_ip/
# Generated by scripts/slim_owned_reject_by_apps.py; tombstones applied
"""


def load_tombstone_hosts(path: Path) -> set[str]:
    hosts: set[str] = set()
    if not path.exists():
        raise SystemExit(f"missing {path}")
    in_ds = False
    for ln in path.read_text(encoding="utf-8").splitlines():
        s = ln.strip()
        if s.startswith("reject_domainset:"):
            in_ds = True
            continue
        if in_ds:
            if s.startswith("-"):
                v = s[1:].strip().strip('"').strip("'")
                if v:
                    hosts.add(v.lower())
                    hosts.add(v.lstrip(".").lower())
            elif s and not s.startswith("#") and ":" in s and not s.startswith("-"):
                break
    return hosts


def load_seed(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def etld1(host: str) -> str:
    h = host.lstrip(".").lower()
    parts = h.split(".")
    if len(parts) < 2:
        return h
    if len(parts) >= 3 and ".".join(parts[-2:]) in MULTI_PART_PUBLIC:
        return ".".join(parts[-3:])
    return ".".join(parts[-2:])


def parent_chain(host: str) -> list[str]:
    parts = host.lstrip(".").lower().split(".")
    return [".".join(parts[i:]) for i in range(len(parts))]


def build_interest(seed: dict) -> tuple[set[str], set[str], list[str], set[str]]:
    domains = {d.lstrip(".").lower() for d in seed.get("domains", []) if d}
    suffixes = {s.lstrip(".").lower() for s in seed.get("suffixes", []) if s}
    needles: set[str] = set()
    for key in ("keywords", "vendors"):
        for v in seed.get(key, []) or []:
            vv = str(v).strip().lower()
            if len(vv) >= 4:
                needles.add(vv)
    for x in seed.get("reject_interest", []) or []:
        xx = str(x).strip().lstrip(".").lower()
        if not xx:
            continue
        if "." in xx:
            suffixes.add(xx)
            domains.add(xx)
        elif len(xx) >= 4:
            needles.add(xx)
    # wildcards → treat base as suffix/needle when possible
    for w in seed.get("wildcards", []) or []:
        ww = str(w).strip().lstrip(".").lower()
        if "*." in ww:
            base = ww.split("*.", 1)[-1]
            if base:
                suffixes.add(base)
        elif "*" in ww:
            # prefix*-*.appsflyersdk.com style
            base = ww.split("*.")[-1] if "*." in ww else ww.replace("*", "").strip(".")
            # e.g. ipyp0a-*.appsflyersdk.com
            m = re.search(r"\*\.([a-z0-9.-]+\.[a-z]{2,})$", ww)
            if m:
                suffixes.add(m.group(1))
            else:
                for part in re.split(r"[.*]+", ww):
                    if len(part) >= 4 and "." not in part:
                        needles.add(part)
    seed_etld = {etld1(x) for x in domains | suffixes}
    needle_list = sorted(needles, key=len, reverse=True)
    return domains, suffixes, needle_list, seed_etld


def is_tombstoned(host: str, tombs: set[str]) -> bool:
    """Exact host match against tombstone set (with/without leading dot)."""
    h = host.lstrip(".").lower()
    return h in tombs or host.lower() in tombs


def host_of_interest(
    host: str,
    domains: set[str],
    suffixes: set[str],
    needles: list[str],
    seed_etld: set[str],
) -> bool:
    h = host.lstrip(".").lower()
    if not h:
        return False
    for p in parent_chain(h):
        if p in domains or p in suffixes:
            return True
    for n in needles:
        if n in h:
            return True
    if etld1(h) in seed_etld:
        return True
    return False


def parse_catalog_interest_apps(path: Path) -> list[tuple[str, str]]:
    """Return list of (folder, name) for surge_interest=true."""
    text = path.read_text(encoding="utf-8")
    apps: list[dict] = []
    current: dict | None = None
    for line in text.splitlines():
        m = re.match(r"^  - name:\s*(.+)$", line)
        if m:
            if current and current.get("name"):
                apps.append(current)
            current = {
                "name": m.group(1).strip().strip('"').strip("'"),
                "folder": "(未分组)",
                "surge_interest": False,
            }
            continue
        if current is None:
            continue
        m2 = re.match(r"^    folder:\s*(.+)$", line)
        if m2:
            current["folder"] = m2.group(1).strip().strip('"').strip("'")
        m3 = re.match(r"^    surge_interest:\s*(true|false)\s*$", line)
        if m3:
            current["surge_interest"] = m3.group(1) == "true"
    if current and current.get("name"):
        apps.append(current)
    out = [
        (a.get("folder") or "(未分组)", a["name"])
        for a in apps
        if a.get("surge_interest")
    ]
    return out


def filter_domainset_line(
    line: str,
    tombs: set[str],
    domains: set[str],
    suffixes: set[str],
    needles: list[str],
    seed_etld: set[str],
) -> str | None:
    """Return line to keep, or None to drop. Blanks/comments dropped (we rewrite header)."""
    s = line.strip()
    if not s or s.startswith("#"):
        return None
    host = s  # domainset: bare host, often with leading dot
    bare = host.lstrip(".")
    if is_tombstoned(bare, tombs) or is_tombstoned(host, tombs):
        return None
    if host_of_interest(bare, domains, suffixes, needles, seed_etld):
        return s
    return None


_DOMAIN_RULE = re.compile(
    r"^(DOMAIN|DOMAIN-SUFFIX|DOMAIN-WILDCARD|DOMAIN-KEYWORD),([^,\s]+)(.*)$",
    re.I,
)


def filter_non_ip_line(
    line: str,
    tombs: set[str],
    domains: set[str],
    suffixes: set[str],
    needles: list[str],
    seed_etld: set[str],
) -> str | None:
    raw = line.rstrip("\n")
    s = raw.strip()
    if not s or s.startswith("#"):
        return None
    m = _DOMAIN_RULE.match(s)
    if not m:
        # IP-CIDR / URL-REGEX / other — keep
        return s
    kind = m.group(1).upper()
    value = m.group(2).strip()
    rest = m.group(3) or ""
    if kind == "DOMAIN-KEYWORD":
        val = value.lower()
        if any(n in val or val in n for n in needles):
            return s
        # also keep if keyword equals a seed domain fragment of interest
        if host_of_interest(val.lstrip("."), domains, suffixes, needles, seed_etld):
            return s
        return None
    # DOMAIN / DOMAIN-SUFFIX / DOMAIN-WILDCARD
    host = value.lstrip(".").replace("*", "").strip(".")
    # DOMAIN-WILDCARD may be *.example.com or *example*
    host_clean = re.sub(r"^\*\.", "", value).replace("*", "").strip(".")
    check = host_clean or host
    if not check:
        return None
    if is_tombstoned(check, tombs):
        return None
    if host_of_interest(check, domains, suffixes, needles, seed_etld):
        return s
    return None


def rebuild_file(
    src: Path,
    dst: Path,
    header: str,
    is_domainset: bool,
    tombs: set[str],
    domains: set[str],
    suffixes: set[str],
    needles: list[str],
    seed_etld: set[str],
) -> tuple[int, int, int]:
    if not src.exists():
        raise SystemExit(f"missing source {src}")
    kept_lines: list[str] = []
    src_rules = 0
    kept = 0
    tomb_hits = 0
    for ln in src.read_text(encoding="utf-8").splitlines():
        s = ln.strip()
        if not s or s.startswith("#"):
            continue
        src_rules += 1
        if is_domainset:
            bare = s.lstrip(".")
            if is_tombstoned(bare, tombs) or is_tombstoned(s, tombs):
                tomb_hits += 1
                continue
            out = filter_domainset_line(ln, tombs, domains, suffixes, needles, seed_etld)
        else:
            m = _DOMAIN_RULE.match(s)
            if m:
                val = m.group(2).strip()
                check = re.sub(r"^\*\.", "", val).replace("*", "").strip(".")
                if check and is_tombstoned(check, tombs):
                    tomb_hits += 1
                    continue
            out = filter_non_ip_line(ln, tombs, domains, suffixes, needles, seed_etld)
        if out is not None:
            kept_lines.append(out)
            kept += 1
    dst.parent.mkdir(parents=True, exist_ok=True)
    body = "\n".join(kept_lines)
    text = header + ("\n" if not header.endswith("\n") else "") + body
    if body:
        text += "\n"
    dst.write_text(text, encoding="utf-8")
    return src_rules, kept, tomb_hits


def write_owned_readme(apps: list[tuple[str, str]]) -> None:
    from collections import defaultdict

    by_folder: dict[str, list[str]] = defaultdict(list)
    for folder, name in apps:
        by_folder[folder].append(name)
    lines = [
        "# mirrors/owned — Option A (V6.1) app-scoped reject",
        "",
        "Runtime `reject*` DOMAIN-SET / RULE-SET in Surge conf point here "
        "(`mirrors/owned/List/...`), **not** at full SKK.",
        "",
        "## What this is",
        "",
        "- **Self-built / curated** `domainset/{reject,reject_extra,reject_phishing}.conf` "
        "and `non_ip/{reject,reject-drop,reject-no-drop}.conf`.",
        "- **Scoped** to apps with `surge_interest: true` in `patches/app_catalog.yaml`, "
        "matched via `patches/interest_seed.json` (domains / suffixes / keywords / vendors).",
        "- **Tombstones** from `patches/tombstones.yaml` are never included "
        "(e.g. `ynuf.aliapp.org`, `amdc.alipay.com`, `logs.amap.com`, "
        "`dualstack-logs.amap.com`). Those hosts are promoted to DIRECT via "
        "`patches/direct-patch.list`.",
        "- Rebuild: `python3 scripts/slim_owned_reject_by_apps.py` "
        "(idempotent; reads SKK cache + seed + tombstones + catalog).",
        "",
        "## Outside this scope",
        "",
        "Owned rejects **only** cover the catalog apps listed below. For other apps / "
        "full ad-block lists, use upstream SKK:",
        "",
        "- https://ruleset.skk.moe",
        "- or local cache: `mirrors/skk/List/domainset/` and `mirrors/skk/List/non_ip/`",
        "",
        "`mirrors/skk` remains an upstream cache for diff / refresh — do **not** delete it.",
        "",
        "## Catalog apps in scope (`surge_interest: true`)",
        "",
        f"Total: **{len(apps)}** apps.",
        "",
    ]
    for folder in sorted(by_folder.keys(), key=lambda x: (x == "(未分组)", x)):
        names = sorted(by_folder[folder])
        lines.append(f"### {folder} ({len(names)})")
        lines.append("")
        for n in names:
            lines.append(f"- {n}")
        lines.append("")
    lines.extend(
        [
            "## Notes",
            "",
            "- Interest absorb / daily bot must **skip** tombstoned hosts "
            "(never re-add into owned reject or ads-patch).",
            "- Do **not** whole-replace owned from upstream without running this slim filter.",
            "- Legacy `scripts/apply_tombstones_owned.py` only stripped tombstones; "
            "prefer `slim_owned_reject_by_apps.py` for V6.1 Option A size.",
            "",
        ]
    )
    OWNED_README.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    tombs = load_tombstone_hosts(TOMB)
    seed = load_seed(SEED)
    domains, suffixes, needles, seed_etld = build_interest(seed)
    apps = parse_catalog_interest_apps(CATALOG)

    print(f"catalog surge_interest apps: {len(apps)}")
    print(f"seed domains={len(domains)} suffixes={len(suffixes)} needles={len(needles)} etld1={len(seed_etld)}")
    print(f"tombstone hosts: {sorted(tombs)}")

    results = []
    for name in DOMAINSET_FILES:
        src = SKK / "domainset" / name
        dst = OWNED / "domainset" / name
        src_n, kept, th = rebuild_file(
            src, dst, HEADER_DOMAINSET, True, tombs, domains, suffixes, needles, seed_etld
        )
        size = dst.stat().st_size
        results.append(("domainset/" + name, src_n, kept, th, size))
        print(f"  domainset/{name}: {src_n} -> {kept} (tomb {th}) {size} bytes")

    for name in NON_IP_FILES:
        src = SKK / "non_ip" / name
        dst = OWNED / "non_ip" / name
        src_n, kept, th = rebuild_file(
            src, dst, HEADER_NON_IP, False, tombs, domains, suffixes, needles, seed_etld
        )
        size = dst.stat().st_size
        results.append(("non_ip/" + name, src_n, kept, th, size))
        print(f"  non_ip/{name}: {src_n} -> {kept} (tomb {th}) {size} bytes")

    write_owned_readme(apps)
    print(f"wrote {OWNED_README}")

    # verify no tombstones remain
    bad = []
    for kind, name in [("domainset", n) for n in DOMAINSET_FILES] + [
        ("non_ip", n) for n in NON_IP_FILES
    ]:
        text = (OWNED / kind / name).read_text(encoding="utf-8").lower()
        for t in tombs:
            tb = t.lstrip(".")
            # line-level check
            for ln in text.splitlines():
                if ln.startswith("#"):
                    continue
                if kind == "domainset":
                    if ln.strip().lstrip(".") == tb:
                        bad.append((kind, name, t, ln))
                else:
                    if re.search(rf",(?:\.)?{re.escape(tb)}(?:[,\s]|$)", ln):
                        bad.append((kind, name, t, ln))
    if bad:
        print("ERROR: tombstones still present:", bad[:10], file=sys.stderr)
        return 1
    print("tombstone check: clean")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
