#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Rebuild mirrors/owned reject* from SKK — app-scoped, no bare short needles.

Keep a SKK reject line only if it passes NEW filter:
  (a) App→tracker map suffix/domain (patches/app_tracker_map.yaml)
  (b) host equals / ends with interest_seed domains/suffixes (full labels)
  (c) reject_interest exact/suffix, or undotted with word-ish label match
  (d) non_ip DOMAIN-KEYWORD / DOMAIN-WILDCARD only when keyword length≥6
      AND matches a safe long keyword (allowlist / seed) with word-ish boundary

Never keep tombstones (patches/tombstones.yaml).
reject_phishing.conf: brand-spoof curated only (finance/AI/social brand tokens).

Idempotent. Does not modify mirrors/skk.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SEED = ROOT / "patches" / "interest_seed.json"
TOMB = ROOT / "patches" / "tombstones.yaml"
CATALOG = ROOT / "patches" / "app_catalog.yaml"
TRACKER_MAP = ROOT / "patches" / "app_tracker_map.yaml"
SKK = ROOT / "mirrors" / "skk" / "List"
OWNED = ROOT / "mirrors" / "owned" / "List"
OWNED_README = ROOT / "mirrors" / "owned" / "README.md"

DOMAINSET_FILES = [
    "reject.conf",
    "reject_extra.conf",
    "reject_phishing.conf",
]
NON_IP_FILES = [
    "reject.conf",
    "reject-drop.conf",
    "reject-no-drop.conf",
]

# Never use these as naked substring needles (over-keep noise like metalex).
BANNED_NAKED_NEEDLES = frozenset(
    {
        "meta",
        "wise",
        "viki",
        "grok",
        "qwen",
        "okex",
        "plasma",
        "venmo",
        "xai",
        "cmb",
        "jd",  # too short; use jd.com suffix instead
        "okx",  # short; phishing uses brand list; seed uses okx.com suffix
    }
)

# Safe long keywords for DOMAIN-KEYWORD / optional host keyword gate (len≥6).
SAFE_LONG_KEYWORDS = frozenset(
    {
        "alipay",
        "tiktok",
        "facebook",
        "bilibili",
        "xiaohongshu",
        "appsflyersdk",
        "tiktokpangle",
        "pglstatp",
        "tobsnssdk",
        "ctobsnssdk",
        "anthropic",
        "chatgpt",
        "openai",
        "paypal",
        "netflix",
        "instagram",
        "youtube",
        "googlevideo",
        "datadoghq",
        "siftscience",
        "featuregates",
        "transferwise",
        "authenticator",
        "braintree",
        "coolapk",
        "pangle",
        "weixin",
        "wechat",
        "taobao",
        "bytedance",
        "douyin",
        "kuaishou",
        "meituan",
        "dianping",
        "biliapi",
        "bilivideo",
        "alibaba",
        "aliapp",
        "snssdk",
        "isnssdk",
        "toutiao",
        "byteoversea",
        "amemv",
        "pangolin",
        "mmstat",
        "alimama",
        "pinduoduo",
        "yangkeduo",
        "elemecdn",
        "tencent",
        "netease",
        "bitget",
        "bitkeep",
        "bybit",
        "uuwallet",
        "statsig",
        "iqiyi",
    }
)

# Phishing brand-spoof tokens (whole-label-ish). No bare "meta".
PHISHING_BRANDS = (
    "alipay",
    "paypal",
    "taobao",
    "google",
    "facebook",
    "apple",
    "microsoft",
    "amazon",
    "binance",
    "okx",
    "bybit",
    "chatgpt",
    "openai",
    "claude",
)

MULTI_PART_PUBLIC = frozenset(
    {
        "com.cn",
        "net.cn",
        "org.cn",
        "gov.cn",
        "co.uk",
        "com.au",
        "co.jp",
        "com.hk",
        "com.tw",
        "com.sg",
        "co.kr",
        "com.br",
        "co.nz",
    }
)

HEADER_DOMAINSET = """\
# owned curated reject DOMAINSET (V6.1 app-scoped)
# 自建精简 reject：catalog surge_interest + app_tracker_map + interest_seed 后缀
# 禁止短裸子串 needle（meta/wise/viki/…）——避免 metalex 等误留
# Tombstones 永不收录；phishing 仅品牌仿冒 curated
# Generated by scripts/slim_owned_reject_by_apps.py
# Source: mirrors/skk (cache only); NOT a full SKK mirror
"""

HEADER_NON_IP = """\
# owned curated reject RULE-SET / non_ip (V6.1 app-scoped)
# 同 domainset：后缀/tracker_map；DOMAIN-KEYWORD 仅长关键词≥6 + allowlist
# Generated by scripts/slim_owned_reject_by_apps.py; tombstones applied
"""

HEADER_PHISHING = """\
# owned curated reject_phishing (V6.1 brand-spoof only)
# 仅保留与用户金融/AI/社交品牌相关的仿冒域名（整标签级匹配）
# brands: alipay paypal taobao google facebook apple microsoft amazon
#         binance okx bybit chatgpt openai claude
# Generated by scripts/slim_owned_reject_by_apps.py
"""


def load_tombstone_hosts(path: Path) -> set[str]:
    hosts: set[str] = set()
    if not path.exists():
        raise SystemExit(f"missing {path}")
    in_ds = False
    for ln in path.read_text(encoding="utf-8").splitlines():
        s = ln.strip()
        if s.startswith("reject_domainset:"):
            in_ds = True
            continue
        if in_ds:
            if s.startswith("-"):
                v = s[1:].strip().strip('"').strip("'")
                if v:
                    hosts.add(v.lower())
                    hosts.add(v.lstrip(".").lower())
            elif s and not s.startswith("#") and ":" in s and not s.startswith("-"):
                break
    return hosts


def load_seed(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def load_tracker_suffixes(path: Path) -> set[str]:
    """Parse app_tracker_map.yaml keep_suffixes without PyYAML."""
    suffixes: set[str] = set()
    if not path.exists():
        raise SystemExit(f"missing {path}")
    in_keep = False
    for ln in path.read_text(encoding="utf-8").splitlines():
        raw = ln.rstrip()
        s = raw.strip()
        if s.startswith("keep_suffixes:"):
            in_keep = True
            continue
        if in_keep:
            if s.startswith("-"):
                v = s[1:].strip().strip('"').strip("'")
                if v:
                    suffixes.add(v.lstrip(".").lower())
                continue
            # end of list when indentation drops to key level or new app field
            if s.startswith("#"):
                continue
            if s and not s.startswith("-"):
                in_keep = False
    return suffixes


def etld1(host: str) -> str:
    h = host.lstrip(".").lower()
    parts = h.split(".")
    if len(parts) < 2:
        return h
    if len(parts) >= 3 and ".".join(parts[-2:]) in MULTI_PART_PUBLIC:
        return ".".join(parts[-3:])
    return ".".join(parts[-2:])


def parent_chain(host: str) -> list[str]:
    parts = host.lstrip(".").lower().split(".")
    return [".".join(parts[i:]) for i in range(len(parts))]


def host_equals_or_ends_with(host: str, suffix: str) -> bool:
    """Full-label suffix match: h == s OR h.endswith('.'+s)."""
    h = host.lstrip(".").lower()
    s = suffix.lstrip(".").lower()
    if not h or not s:
        return False
    return h == s or h.endswith("." + s)


def wordish_label_match(host: str, token: str) -> bool:
    """True if token appears as whole label or label prefix/suffix (not mid-string)."""
    tok = token.lower().strip(".")
    if not tok:
        return False
    h = host.lstrip(".").lower()
    for lab in h.split("."):
        if not lab:
            continue
        if lab == tok or lab.startswith(tok) or lab.endswith(tok):
            return True
        # hyphen-separated: foo-tok-bar
        parts = lab.split("-")
        if tok in parts:
            return True
    return False


def is_banned_needle(n: str) -> bool:
    nn = n.strip().lower()
    if not nn:
        return True
    if nn in BANNED_NAKED_NEEDLES:
        return True
    if len(nn) <= 5:
        return True
    return False


def build_interest(seed: dict) -> tuple[set[str], set[str], set[str], list[str]]:
    """Return domains, suffixes, reject_kw (undotted), safe_kw_list for KEYWORD rules."""
    domains = {d.lstrip(".").lower() for d in seed.get("domains", []) if d}
    suffixes = {s.lstrip(".").lower() for s in seed.get("suffixes", []) if s}
    reject_kw: set[str] = set()

    for x in seed.get("reject_interest", []) or []:
        xx = str(x).strip().lstrip(".").lower()
        if not xx:
            continue
        if "." in xx:
            suffixes.add(xx)
            domains.add(xx)
        else:
            # undotted reject_interest (e.g. pangolin) — word-ish only, never bare ≤5
            if not is_banned_needle(xx):
                reject_kw.add(xx)

    for w in seed.get("wildcards", []) or []:
        ww = str(w).strip().lstrip(".").lower()
        m = re.search(r"\*\.([a-z0-9.-]+\.[a-z]{2,})$", ww)
        if m:
            suffixes.add(m.group(1))
        elif "*." in ww:
            base = ww.split("*.", 1)[-1]
            if base and "." in base:
                suffixes.add(base)

    # Safe long keywords for DOMAIN-KEYWORD only (never for domainset substring).
    safe: set[str] = set(SAFE_LONG_KEYWORDS)
    for key in ("keywords", "vendors"):
        for v in seed.get(key, []) or []:
            vv = str(v).strip().lower()
            if is_banned_needle(vv):
                continue
            if len(vv) >= 6:
                safe.add(vv)
    for x in seed.get("reject_interest", []) or []:
        xx = str(x).strip().lstrip(".").lower()
        if xx and "." not in xx and not is_banned_needle(xx):
            safe.add(xx)

    safe_list = sorted(safe, key=len, reverse=True)
    return domains, suffixes, reject_kw, safe_list


def is_tombstoned(host: str, tombs: set[str]) -> bool:
    h = host.lstrip(".").lower()
    return h in tombs or host.lower() in tombs


def host_of_interest(
    host: str,
    domains: set[str],
    suffixes: set[str],
    tracker_suffixes: set[str],
    reject_kw: set[str],
) -> bool:
    """Keep host if seed domain/suffix OR tracker map OR reject_interest wordish."""
    h = host.lstrip(".").lower()
    if not h:
        return False
    for p in parent_chain(h):
        if p in domains or p in suffixes:
            return True
    for s in suffixes | domains | tracker_suffixes:
        if host_equals_or_ends_with(h, s):
            return True
    for kw in reject_kw:
        if wordish_label_match(h, kw):
            return True
    return False


def phishing_brand_hit(host: str) -> bool:
    h = host.lstrip(".").lower()
    if not h:
        return False
    for brand in PHISHING_BRANDS:
        if wordish_label_match(h, brand):
            return True
    return False


def parse_catalog_interest_apps(path: Path) -> list[tuple[str, str]]:
    text = path.read_text(encoding="utf-8")
    apps: list[dict] = []
    current: dict | None = None
    for line in text.splitlines():
        m = re.match(r"^  - name:\s*(.+)$", line)
        if m:
            if current and current.get("name"):
                apps.append(current)
            current = {
                "name": m.group(1).strip().strip('"').strip("'"),
                "folder": "(未分组)",
                "surge_interest": False,
            }
            continue
        if current is None:
            continue
        m2 = re.match(r"^    folder:\s*(.+)$", line)
        if m2:
            current["folder"] = m2.group(1).strip().strip('"').strip("'")
        m3 = re.match(r"^    surge_interest:\s*(true|false)\s*$", line)
        if m3:
            current["surge_interest"] = m3.group(1) == "true"
    if current and current.get("name"):
        apps.append(current)
    return [
        (a.get("folder") or "(未分组)", a["name"])
        for a in apps
        if a.get("surge_interest")
    ]


_DOMAIN_RULE = re.compile(
    r"^(DOMAIN|DOMAIN-SUFFIX|DOMAIN-WILDCARD|DOMAIN-KEYWORD),([^,\s]+)(.*)$",
    re.I,
)


def keyword_allowed(val: str, safe_list: list[str]) -> bool:
    """DOMAIN-KEYWORD: length≥6 and matches safe keyword with word-ish boundary."""
    v = val.lower().strip()
    if len(v) < 6:
        return False
    for kw in safe_list:
        if len(kw) < 6:
            continue
        if v == kw:
            return True
        # word-ish: keyword as substring with non-alnum boundaries or ends
        if re.search(
            rf"(^|[^a-z0-9]){re.escape(kw)}([^a-z0-9]|$)", v
        ) or v.startswith(kw) or v.endswith(kw):
            return True
        # also allow if keyword contains the value as full token (rare)
        if kw == v:
            return True
    return False


def filter_domainset_line(
    line: str,
    tombs: set[str],
    domains: set[str],
    suffixes: set[str],
    tracker_suffixes: set[str],
    reject_kw: set[str],
    *,
    phishing: bool = False,
) -> str | None:
    s = line.strip()
    if not s or s.startswith("#"):
        return None
    host = s
    bare = host.lstrip(".")
    if is_tombstoned(bare, tombs) or is_tombstoned(host, tombs):
        return None
    if phishing:
        return s if phishing_brand_hit(bare) else None
    if host_of_interest(bare, domains, suffixes, tracker_suffixes, reject_kw):
        return s
    return None


def filter_non_ip_line(
    line: str,
    tombs: set[str],
    domains: set[str],
    suffixes: set[str],
    tracker_suffixes: set[str],
    reject_kw: set[str],
    safe_list: list[str],
) -> str | None:
    raw = line.rstrip("\n")
    s = raw.strip()
    if not s or s.startswith("#"):
        return None
    m = _DOMAIN_RULE.match(s)
    if not m:
        # IP-CIDR / URL-REGEX / other — keep (rare; not substring-noise)
        return s
    kind = m.group(1).upper()
    value = m.group(2).strip()
    if kind == "DOMAIN-KEYWORD":
        if keyword_allowed(value, safe_list):
            return s
        return None
    # DOMAIN / DOMAIN-SUFFIX / DOMAIN-WILDCARD
    host_clean = re.sub(r"^\*\.", "", value).replace("*", "").strip(".")
    check = host_clean
    if not check:
        return None
    if is_tombstoned(check, tombs):
        return None
    if kind == "DOMAIN-WILDCARD" and "*" in value and "." not in value.replace("*", ""):
        # pure keyword-like wildcard — treat as keyword
        kw = value.replace("*", "").lower()
        if keyword_allowed(kw, safe_list):
            return s
        return None
    if host_of_interest(check, domains, suffixes, tracker_suffixes, reject_kw):
        return s
    return None


def rebuild_file(
    src: Path,
    dst: Path,
    header: str,
    is_domainset: bool,
    tombs: set[str],
    domains: set[str],
    suffixes: set[str],
    tracker_suffixes: set[str],
    reject_kw: set[str],
    safe_list: list[str],
    *,
    phishing: bool = False,
) -> tuple[int, int, int]:
    if not src.exists():
        raise SystemExit(f"missing source {src}")
    kept_lines: list[str] = []
    src_rules = 0
    kept = 0
    tomb_hits = 0
    for ln in src.read_text(encoding="utf-8").splitlines():
        s = ln.strip()
        if not s or s.startswith("#"):
            continue
        src_rules += 1
        if is_domainset:
            bare = s.lstrip(".")
            if is_tombstoned(bare, tombs) or is_tombstoned(s, tombs):
                tomb_hits += 1
                continue
            out = filter_domainset_line(
                ln,
                tombs,
                domains,
                suffixes,
                tracker_suffixes,
                reject_kw,
                phishing=phishing,
            )
        else:
            m = _DOMAIN_RULE.match(s)
            if m:
                val = m.group(2).strip()
                check = re.sub(r"^\*\.", "", val).replace("*", "").strip(".")
                if check and is_tombstoned(check, tombs):
                    tomb_hits += 1
                    continue
            out = filter_non_ip_line(
                ln,
                tombs,
                domains,
                suffixes,
                tracker_suffixes,
                reject_kw,
                safe_list,
            )
        if out is not None:
            kept_lines.append(out)
            kept += 1
    dst.parent.mkdir(parents=True, exist_ok=True)
    body = "\n".join(kept_lines)
    text = header + ("\n" if not header.endswith("\n") else "") + body
    if body:
        text += "\n"
    dst.write_text(text, encoding="utf-8")
    return src_rules, kept, tomb_hits


def write_owned_readme(
    apps: list[tuple[str, str]],
    tracker_suffixes: set[str],
    tombs: set[str],
) -> None:
    from collections import defaultdict

    by_folder: dict[str, list[str]] = defaultdict(list)
    for folder, name in apps:
        by_folder[folder].append(name)

    tomb_list = ", ".join(f"`{t}`" for t in sorted({x.lstrip(".") for x in tombs}))
    tracker_list = ", ".join(f"`{s}`" for s in sorted(tracker_suffixes))

    lines = [
        "# mirrors/owned — V6.1 自建精简 reject（Option A）",
        "",
        "运行时 Surge 的 `reject*` DOMAIN-SET / RULE-SET 指向此处"
        "（`mirrors/owned/List/...`），**不是**完整 SKK。",
        "",
        "## 本次策略变更（精简误删 / 误留修复）",
        "",
        "- **停止**使用短裸子串 needle 做 keep 判断：禁止 `meta` / `wise` / `viki` /"
        " `grok` / `qwen` / `okex` / `plasma` / `venmo` 等（长度≤5 或显式黑名单）。"
        " 由此 `metalex.io` / `metamx` 一类噪声不再因 `meta` 误留。",
        "- **Keep 条件**（从空集合重建）：",
        "  1. `patches/app_tracker_map.yaml` 中的 tracker 后缀/域名（整标签匹配）；",
        "  2. `interest_seed.json` 的 domains / suffixes（整标签 equals / ends-with）；",
        "  3. `reject_interest` 精确/后缀，或无点关键词的整标签级匹配（如 `pangolin`）；",
        "  4. non_ip 的 `DOMAIN-KEYWORD` / 类关键词 `DOMAIN-WILDCARD`：仅当关键词长度≥6"
        " 且命中安全长词 allowlist（如 alipay、tiktok、facebook、bilibili）。",
        "- **Tombstones**（永不进 owned reject，并写入 `direct-patch` → DIRECT）："
        f" {tomb_list}。",
        "- **reject_phishing**：仅保留金融/AI/社交品牌仿冒（alipay、paypal、taobao、"
        "google、facebook、apple、microsoft、amazon、binance、okx、bybit、chatgpt、"
        "openai、claude），整标签级匹配；文件显著变小。",
        f"- **Tracker map 后缀**：{tracker_list}。",
        "- 重建命令：`python3 scripts/slim_owned_reject_by_apps.py`（幂等）。",
        "",
        "## 范围外",
        "",
        "Owned 只覆盖下方 catalog `surge_interest: true` 的 App 及相关 tracker。"
        "其他 App / 完整广告列表请用上游 SKK：",
        "",
        "- https://ruleset.skk.moe",
        "- 或本地缓存：`mirrors/skk/List/domainset/` 与 `mirrors/skk/List/non_ip/`",
        "",
        "`mirrors/skk` 仍作上游缓存，供 diff / 刷新 — **不要删除**。",
        "",
        "## Catalog 覆盖范围（`surge_interest: true`）",
        "",
        f"合计：**{len(apps)}** 个 App。",
        "",
    ]
    for folder in sorted(by_folder.keys(), key=lambda x: (x == "(未分组)", x)):
        names = sorted(by_folder[folder])
        lines.append(f"### {folder} ({len(names)})")
        lines.append("")
        for n in names:
            lines.append(f"- {n}")
        lines.append("")
    lines.extend(
        [
            "## 注意",
            "",
            "- 兴趣吸收 / daily bot **不得**把 tombstone 主机写回 owned reject 或 ads-patch。",
            "- **禁止**在未跑本精简脚本的情况下整包覆盖 owned。",
            "- 旧脚本 `apply_tombstones_owned.py` 仅剥 tombstone；V6.1 请用本脚本。",
            "",
        ]
    )
    OWNED_README.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    tombs = load_tombstone_hosts(TOMB)
    seed = load_seed(SEED)
    tracker_suffixes = load_tracker_suffixes(TRACKER_MAP)
    domains, suffixes, reject_kw, safe_list = build_interest(seed)
    # Merge tracker into matching set (also available separately for README)
    apps = parse_catalog_interest_apps(CATALOG)

    print(f"catalog surge_interest apps: {len(apps)}")
    print(
        f"seed domains={len(domains)} suffixes={len(suffixes)} "
        f"reject_kw={len(reject_kw)} safe_kw={len(safe_list)} "
        f"tracker_suffixes={len(tracker_suffixes)}"
    )
    print(f"tombstone hosts: {sorted(tombs)}")
    print(f"banned naked needles: {sorted(BANNED_NAKED_NEEDLES)}")

    results = []
    for name in DOMAINSET_FILES:
        src = SKK / "domainset" / name
        dst = OWNED / "domainset" / name
        is_phish = name == "reject_phishing.conf"
        hdr = HEADER_PHISHING if is_phish else HEADER_DOMAINSET
        src_n, kept, th = rebuild_file(
            src,
            dst,
            hdr,
            True,
            tombs,
            domains,
            suffixes,
            tracker_suffixes,
            reject_kw,
            safe_list,
            phishing=is_phish,
        )
        size = dst.stat().st_size
        results.append(("domainset/" + name, src_n, kept, th, size))
        print(f"  domainset/{name}: {src_n} -> {kept} (tomb {th}) {size} bytes")

    for name in NON_IP_FILES:
        src = SKK / "non_ip" / name
        dst = OWNED / "non_ip" / name
        src_n, kept, th = rebuild_file(
            src,
            dst,
            HEADER_NON_IP,
            False,
            tombs,
            domains,
            suffixes,
            tracker_suffixes,
            reject_kw,
            safe_list,
        )
        size = dst.stat().st_size
        results.append(("non_ip/" + name, src_n, kept, th, size))
        print(f"  non_ip/{name}: {src_n} -> {kept} (tomb {th}) {size} bytes")

    write_owned_readme(apps, tracker_suffixes, tombs)
    print(f"wrote {OWNED_README}")

    # verify no tombstones remain
    bad = []
    for kind, name in [("domainset", n) for n in DOMAINSET_FILES] + [
        ("non_ip", n) for n in NON_IP_FILES
    ]:
        text = (OWNED / kind / name).read_text(encoding="utf-8").lower()
        for t in tombs:
            tb = t.lstrip(".")
            for ln in text.splitlines():
                if ln.startswith("#"):
                    continue
                if kind == "domainset":
                    if ln.strip().lstrip(".") == tb:
                        bad.append((kind, name, t, ln))
                else:
                    if re.search(rf",(?:\.)?{re.escape(tb)}(?:[,\s]|$)", ln):
                        bad.append((kind, name, t, ln))
    if bad:
        print("ERROR: tombstones still present:", bad[:10], file=sys.stderr)
        return 1
    print("tombstone check: clean")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
